### ISSUE TITLE
Add -config flag

### ISSUE THREAD

**Issue by yonas** [TimoKats/mdrss#19]
Created PR #18

**Comment by TimoKats** [comment]
@yonas thanks for the PR, and a good idea! I'll have a closer look (and merge it) tomorrow when I have access to my laptop again.

**Comment by TimoKats** [comment]
This has been merged btw. Your co-author of the PR

**Comment by yonas** [comment]
Thanks!

Are you not a fan of XDG? More Unix apps are supporting it these days.

**Comment by TimoKats** [comment]
@yonas Oh yeah that's right. I did look at the repo and it should work for mdrss yes. However, it would be an external library for something I now do with native go stuff. 

For most people that's fine btw, but personally I prefer to be minimal with external libraries if possible.
