### ISSUE TITLE
Install using go install command

### ISSUE THREAD

**Issue by pk0dev** [TimoKats/mdrss#6]
unable to install this application using `go install github.com/TimoKats/mdrss` command.

It throws error as below:
`go: 'go install' requires a version when current directory is not in a module`
        `Try 'go install github.com/TimoKats/mdrss@latest' to install the latest version`
        
        
and so I tried with the `@latest` at the end as below.
`go install github.com/TimoKats/mdrss@latest`

and it throws the below error:
`go: downloading github.com/TimoKats/mdrss v0.0.0-20240731121216-dceaef5ce79a`
`go: github.com/TimoKats/mdrss@latest: version constraints conflict:`
        `github.com/TimoKats/mdrss@v0.0.0-20240731121216-dceaef5ce79a: parsing go.mod:`
        `module declares its path as: mdrss`
               `but was required as: github.com/TimoKats/mdrss`

**Comment by pk0dev** [comment]
Hey @TimoKats I really love the idea of converting markdown files into RSS. I don't know much of GoLang but I guess I should be able to download your application using `go install command`.

**Comment by TimoKats** [comment]
Hey Pravin. Thanks for the heads up. I'm looking into this now. For me, `go install` works when I run it in the working directory. If I use the github URL (as you do in your example), I get the same error.

Hence, for the time being, you could do the following. Git clone the repository, and run `go install` or `go build` there. After this, you should be able to use `mdrss` from the command line. Note, you still need to manually setup the config file after this (See README). 

PS: I will look into this later this week to come up with a more sustainable solution. If you run into anything else, please let me know. Thanks!

**Comment by pk0dev** [comment]
Hey @TimoKats thank you for that. I have installed mdrss and am facing an issue.

I've added the config file as per the READ.md and when I run `mdrss my_first_blog.md` I'm getting the below error.
`$ mdrss first_blog.md`
`ERROR:    00:39:42 mdrss.go:58: Config file not found.`

I've also tried `mdrss ls`, `mdrss draft` and `mdrss conf` but getting similar errors.

**Comment by pk0dev** [comment]
I'll try to get some folks who could contribute to this project.

**Comment by TimoKats** [comment]
That error message is correct. This is mentioned in the README, but the program expects a config file in `~/.mdrss/config.json`. You can find an example in the README with the field that it expects. I can imagine it's a bit manual to set up like this, but I initially made the program for personal usage only so things like these happen :)

```json
  {
    "Author": "Timo Kats",
    "Description": "Timo's weblog",
    "InputFolder": "/path/to/articles/", # This will contain your markdown files
    "OutputFile": "/path/to/webserver/index.xml",
    "Link": "index.xml" # can be anything, might be deprecated
  }
```

**Comment by TimoKats** [comment]
I'll make the error messages a bit more informative.

**Comment by pk0dev** [comment]
> @pk0dev that error message is correct. The README is wrong I see now. The program expects a config file in `~/.mdrss/config.json`. Not `~/.mdrss/config`. Will fix that!

Oh okay, Thank you

**Comment by pk0dev** [comment]
Hey @TimoKats, I did it. I published my first RSS thanks to you. :partying_face: 

```
Feed: Pravin's Blog
Title: This is my first blog
Date: Wed, 01 Jan 2014 05:30:00 +0530
Link: https://pk0dev.github.io/feed/index.xml

I'm planning to write at least one blog a week. I'll try to share all my learning of the week, interesting finds and my experiences. This would be a tool to reflect
back on how far I've come whenever I feel low or to motivate myself.

I hope you I add some value with my blogs.

Thanks to [Timo Kats](https://github.com/TimoKats), I'm wring my first RSS feed using his project on github called [mdrss](https://github.com/TimoKats/mdrss).

pk0dev [dot] github [dot] io
```

**Comment by TimoKats** [comment]
Hello. I just tested this morning and go install worked for me. Make sure that GOPATH and all are set correctly and you should get the following result. I think there was some caching issue with my fix yesterday evening because now it works without changing it.

![image](https://github.com/user-attachments/assets/64ab5b22-ed16-47ce-9b23-28651853e305)

**Comment by pk0dev** [comment]
I see. I will check the go env and path. Go works fine for other packages. Honestly Go is the only thing which I find a bit tricky to set up compared to other languages and softwares.

**Comment by TimoKats** [comment]
@pk0dev . It didn't work for me yesterday either. But it works today. My conclusion, I think it takes some time before `go install` gets the updated version. I also noticed this today when I wanted to change the datetime format for the other issue you had. 

So if you run `go install github.com/TimoKats/mdrss@latest` now, does it work?

**Comment by pk0dev** [comment]
It works now! :tada:  Thank you @TimoKats

**Comment by pk0dev** [comment]
Issue resolved

Now able to download the project using `go install github.com/TimoKats/mdrss@latest`
