### ISSUE TITLE
[Feature Request] Option to add title per markdown file

### ISSUE THREAD

**Issue by pk0dev** [TimoKats/mdrss#8]
currently this is how the RSS header looks like:
```
Feed: Pravin's Blog
Title: This is my first blog
Date: Wed, 01 Jan 2014 05:30:00 +0530
Link: https://pk0dev.github.io/feed/index.xml
```
It would be really nice to set the title per markdown file.

For example:
`mdrss blog1.md -T "This is the title for blog 1"`

and the rss file can be updated using the `mdrss update` command

**Comment by TimoKats** [comment]
Hey @pk0dev , the title is derived from the markdown title. With other words, you can start your article like this:

```markdown
# This is a title that mdrss will use

Here I will write my blog.
```

That title is correct than right? Or would you like the title in the feed to differ from the title in markdown?

**Comment by pk0dev** [comment]
Got it, thanks for the clarification. You are right the title of the blog should be the first Header in the markdown file.
