### ISSUE TITLE
[Bug] Current date needs to be updated in the blog header

### ISSUE THREAD

**Issue by pk0dev** [TimoKats/mdrss#9]
currently the date in the the RSS header is not correct:
```
Feed: Pravin's Blog
Title: This is my first blog
Date: Wed, 01 Jan 2014 05:30:00 +0530
Link: https://pk0dev.github.io/feed/index.xml
```

The current date to be added on `mdrss update` command for every new markdown file added

**Comment by TimoKats** [comment]
Hey @pk0dev , that's definitely not correct, and not the behavior that I have. Checking it out now!  As a check, the code bases the date of an article on the last modified date of its markdown file. So you can check what the datetime is there?

```go
  article.DatePublished = fileInfo.ModTime()
```

**Comment by pk0dev** [comment]
when I perform the `ls -l` the markdown file last modified date and time shows of today

`-rw-r--r-- 1 pk0dev pk0dev 490 Aug 14 13:04 1.my_first_blog.md`

**Comment by TimoKats** [comment]
Ok I will look into this today (probably in the evening) to fix this. Because it's quite a big issue. As a final check: could you run `date` on your machine and check the result? Finally, what OS and go version are you using?

**Comment by TimoKats** [comment]
Hmmm it's strange, because the rss file itself seems to have the correct dates. Perhaps the time zone breaks it?

```XML
<title>Pravin's Blog</title>
<author>Pravin Kumar</author>
<link>rss.xml</link>
<lastBuildDate>14 Aug 24 13:04 IST</lastBuildDate>
<description>Pravin's Blog</description>
```

**Comment by pk0dev** [comment]
I'm using `newsboat` on `LMDE` and `go version go1.22.4 linux/amd64`. The `date` command shows me the accurate date and time.

**Comment by TimoKats** [comment]
@pk0dev . Hello. I made an update today to change the datetime format of the pubDate from RFC822 to RFC822Z. This might resolve the issue, since it's the format I see in most RSS feed XMLs. For me it works either way. Let me know if this version resolves your issue.

**Comment by pk0dev** [comment]
Nice. I'll test it soon when I write my next blog.

**Comment by TimoKats** [comment]
Good :+1: If you do `mdrss update` now, it should update the feed with the same articles but with improved timestamps, support for links, and unordered lists. So hopefully that works for you too.

**Comment by TimoKats** [comment]
I subscribed to your RSS feed to check and the dates seem ok. The links in the second post are also normally formatted. Small sidenote if you're using `newsboat`. It sometimes caches old results, hence it might seem like there are more blogposts after we fixed the dates. Hence, you can remove `~/.newsboat/cache.db` to fix this if you want.

**Comment by pk0dev** [comment]
Yes, I did remove the newsboat cache to load the rss feed as new load and seems it worked. Thanks.

I did also notice that at the bottom of the blog it shows the links which could be really handy. Nice feature

I agree haveing `guid` would makes the job much better as it will apend only for new post.
